import { Geist, Geist_Mono } from "next/font/google";
import { UserProvider } from "@/hooks/useUser";
import { MessageProvider } from "@/hooks/useMessage";
import { ThemeModeScript, ThemeProvider, createTheme } from "flowbite-react";
import fetchDefaultBroker from "@/client-services/preference/defaultBroker";
import Navbar from "@/components/navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const customTheme = createTheme({
  avatar: {
    root: {
      img: {
        base: "rounded object-cover",
      },
    },
  },
});

export default async function RootLayout({ children }) {
  const defaultBroker = await fetchDefaultBroker();

  return (
    <html>
      <head>
        <ThemeModeScript />
      </head>
      <body className={`min-h-screen bg-gradient-to-br from-pink-50 to-purple-50 ${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider theme={customTheme}>
          <MessageProvider>
            <UserProvider defaultBroker={defaultBroker}>
              <Navbar />
              {children}
            </UserProvider>
          </MessageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
