import { Geist, Geist_Mono } from "next/font/google";
import { UserProvider } from "@/hooks/useUser";
import { MessageProvider } from "@/hooks/useMessage";
import { ThemeModeScript } from "flowbite-react";
import Navbar from "@/components/navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="min-h-screen bg-gradient-to-br from-pink-50 to-purple-50">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeModeScript />
        <MessageProvider>
          <UserProvider>
            <Navbar />
            {children}
          </UserProvider>
        </MessageProvider>
      </body>
    </html>
  );
}
